# Generated by Django 4.0.3 on 2022-04-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_teachers_email_alter_teachers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
